---
# Source: sbapp-cicd/templates/configmap-file.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-uat-t24-appapi-v2-file
  labels:
    app.kubernetes.io/app: appapi
    app.kubernetes.io/instance: sb-uat-t24-appapi-v2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: v2
    context.platform.io/env: uat
    context.platform.io/org: sb
    context.platform.io/system: t24
    helm.sh/chart: sbapp-cicd-0.1.1
  annotations:
    {}
data:
  app.js: |
    123
    456
  list.txt: |
    23123
    123123123
