{{- if and .Values.service.enabled (include "chart.isDeployment" . | eq "true" ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.serviceName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- include "chart.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
